require:
  - rubocop-performance
  - rubocop-rspec

inherit_mode:
  merge:
    - Include
    - Exclude

Layout/IndentationStyle:
  EnforcedStyle: tabs
  IndentationWidth: 2
Layout/IndentationWidth:
  Width: 1
Layout/LineLength:
  Max: 100
Layout/MultilineMethodCallIndentation:
  EnforcedStyle: indented
Layout/MultilineOperationIndentation:
  EnforcedStyle: indented
Layout/ArgumentAlignment:
  EnforcedStyle: with_fixed_indentation
Layout/ParameterAlignment:
  EnforcedStyle: with_fixed_indentation
Layout/FirstArgumentIndentation:
  EnforcedStyle: consistent
Layout/FirstParameterIndentation:
  EnforcedStyle: consistent
Layout/FirstArrayElementIndentation:
  EnforcedStyle: consistent
Layout/FirstHashElementIndentation:
  EnforcedStyle: consistent
Layout/MultilineArrayBraceLayout:
  EnforcedStyle: new_line
Layout/MultilineHashBraceLayout:
  EnforcedStyle: new_line

Metrics/BlockLength:
  Exclude:
    - '*.gemspec'
    - spec/**/*.rb
    - lib/gem_toys/template.rb
    - lib/gem_toys/template/*.rb

AllCops:
  TargetRubyVersion: 3.0
  NewCops: enable

RSpec/NestedGroups:
  Max: 4
